version: '3.5'
services:
  parser-service:
    image: ghcr.io/news-aggregator-bot/picky.parser-service
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9055/actuator/health" ]
      interval: 60s
      timeout: 5s
      retries: 3
    ports:
      - 9055:9055
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "500M"
        reservations:
          cpus: "0.5"
          memory: "200M"
networks:
  default:
    external:
      name: picky
