server:
  port: 9055
spring:
  application:
    name: na-data-reader-service
  main:
    banner-mode: "off"
  config:
    import: "optional:"
    activate:
      on-profile: ${SPRING_PROFILES_ACTIVE}
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      FAIL_ON_EMPTY_BEANS: false
      FAIL_ON_SELF_REFERENCES: false
  cloud:
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    org.springframework.security: INFO
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
subject:
  parse: parse