server:
  port: 9055
spring:
  application:
    name: parser-service
  main:
    banner-mode: "off"
  config:
    import: "optional:"
    activate:
      on-profile: ${SPRING_PROFILES_ACTIVE}
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      FAIL_ON_EMPTY_BEANS: false
      FAIL_ON_SELF_REFERENCES: false
  cloud:
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    org.springframework.security: INFO
    com.gargoylesoftware.htmlunit: OFF
#    org:
#      hibernate:
#        SQL: debug
#        type:
#          descriptor:
#            sql: trace
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
subject:
  parse: parse
read:
  timeout: 30
nats:
  address: 'na-ts:4222'